<?php
/**
 * Copyright (c) 2025. Volodymyr Hryvinskyi. All rights reserved.
 * Author: Volodymyr Hryvinskyi <volodymyr@hryvinskyi.com>
 * GitHub: https://github.com/hryvinskyi
 */

declare(strict_types=1);

/** @var \Magento\Framework\View\Element\Template $block */

echo $block->getChildHtml('before_head_additional');
echo '<' . '!-- {{HRYVINSKYI:PLACEHOLDER:HEAD_ADDITIONAL}} --' . '>';
echo $block->getChildHtml('after_head_additional');